# 2022-07-31 13:56 Ogn.
# 2022-08-14 12:30 Ogn.

title: Smolenishev.github.io blog. Блог Смоленышева Олега
description: Дневник и заметки по изучению keras, fastai и т.д.
github_username: Smolenishev

# Email and twitter are optional:
email: smolenishev@mail.ru

# Set this to true to get LaTeX math equation support
use_math: True

# Add your Google Analytics ID here if you have one and want to use it
google_analytics: smolenishev

# Everything below here can be ignored, unless you want to change the theme entirely
# theme: minima
# plugins:
#   - jekyll-feed
#   - jekyll-gist
#   - jekyll-octicons
#   - jekyll-github-metadata

# titles_from_headings:
#   enabled:     true
#   strip_title: true
#   collections: true

# highlighter: rouge
# markdown: kramdown
# kramdown:
#   math_engine: katex
#   input: GFM
#   auto_ids: true
#   hard_wrap: false
#   syntax_highlighter: rouge
